# -*- mode: org; fill-column: 78; -*-
# Time-stamp: <2022-10-30 21:59:55 krylon>
#
#+TAGS: optimize(o) refactor(r) bug(b) feature(f) architecture(a)
#+TAGS: web(w) database(d) javascript(j)
#+TODO: TODO(t) IMPLEMENT(i) TEST(e) RESEARCH(r) | DONE(d)
#+TODO: MEDITATE(m) PLANNING(p) REFINE(n) | FAILED(f) CANCELLED(c) SUSPENDED(s)
#+TODO: EXPERIMENT(x) |
#+PRIORITIES: A G D

* Guang
** Clocktable
   #+BEGIN: clocktable :scope file :maxlevel 20
   #+CAPTION: Clock summary at [2022-10-30 So 21:59]
   | Headline                    | Time    |       |      |      |      |
   |-----------------------------+---------+-------+------+------+------|
   | *Total time*                | *14:14* |       |      |      |      |
   |-----------------------------+---------+-------+------+------+------|
   | Guang                       | 14:14   |       |      |      |      |
   | \_  Components              |         | 14:14 |      |      |      |
   | \_    Database              |         |       | 0:47 |      |      |
   | \_      SQLite              |         |       |      | 0:44 |      |
   | \_      Major cleanup [1/2] |         |       |      | 0:03 |      |
   | \_        Package           |         |       |      |      | 0:03 |
   | \_    Web interface         |         |       | 4:15 |      |      |
   | \_      Embed               |         |       |      | 4:15 |      |
   | \_    Refactoring [0/2]     |         |       | 9:12 |      |      |
   | \_      Packages            |         |       |      | 7:38 |      |
   | \_      Linter              |         |       |      | 1:34 |      |
   #+END:
** Diary
*** [2022-10-26 Mi 15:56]
    I haven't touched this code in a pretty long time, before I can move on,
    I'm going to reorganize it so it conforms to the layout I used in my more
    recent projects, plus the web interface is going to need *a lot* of work.
** Components
*** Database
**** DONE SQLite
     CLOSED: [2022-10-27 Do 18:36]
     :LOGBOOK:
     CLOCK: [2022-10-27 Do 17:52]--[2022-10-27 Do 18:36] =>  0:44
     :END:
     The library I use for the SQLite bindings is kind of out of date, I think
**** TODO Pool
**** Major cleanup [1/2]                                           :refactor:
     I need to fix/refactor a couple of things.
***** DONE Package
      CLOSED: [2022-10-27 Do 19:45]
      :LOGBOOK:
      CLOCK: [2022-10-27 Do 19:41]--[2022-10-27 Do 19:44] =>  0:03
      :END:
      I need to move the database into a separate package
***** TODO Names
      I need to change a bunch of names.
*** Web interface
**** DONE Embed
     CLOSED: [2022-10-26 Mi 20:42]
     :LOGBOOK:
     CLOCK: [2022-10-26 Mi 16:27]--[2022-10-26 Mi 20:42] =>  4:15
     :END:
     I use a Perl script to roll all of my assets into a Go variable, which
     became unneccessary when Go gained go:embed. Still need to make a few
     adjustments to make that step, then I can remove the script.
*** Refactoring [0/2]                                              :refactor:
**** TODO Packages
     :LOGBOOK:
     CLOCK: [2022-10-29 Sa 18:01]--[2022-10-30 So 00:33] =>  6:32
     CLOCK: [2022-10-27 Do 19:45]--[2022-10-27 Do 20:51] =>  1:06
     :END:
     I need break up the application into more packages, the current state is
     just repulsive from an aesthetic perspective.
**** TODO Linter
     :LOGBOOK:
     CLOCK: [2022-10-30 So 20:25]--[2022-10-30 So 21:59] =>  1:34
     :END:
     Apparently I was not in the habit of using a linter when I wrote guang
     initially. So I have to do a lot of simple but tedious work to do.
** Bugs
